import { useEffect, useMemo, useState } from 'react';
import { api } from './api/client';
import { openEventSocket } from './api/ws';
import Header from './components/Header';
import ConsentBanner from './components/ConsentBanner';
import StatusView from './components/StatusView';
import type { AuditEvent, ExportBundleRecord, OperatorSession, PluginDefinition, RelayJob, TargetAllowlistEntry } from './types';
import { downloadJson, formatDate, statusClass } from './utils/formatters';
import { cacheGet, cacheSet } from './lib/indexedDb';

function can(session: OperatorSession | null, permission: string) { return !!session?.permissions?.includes(permission as never); }
function initialPage() { return window.location.hash.replace('#/', '') || 'dashboard'; }
const emptyTarget = { hostname: '', address: '', protocol: 'smb', port: 445, scopeTag: '', notes: '', expiresAt: null as string | null };

export default function App() {
  const [page, setPageState] = useState(initialPage());
  const [session, setSession] = useState<OperatorSession | null>(() => { try { return JSON.parse(localStorage.getItem('relayjack.session') || 'null'); } catch { return null; } });
  const [online, setOnline] = useState(navigator.onLine);
  const [wsState, setWsState] = useState('closed');
  const [notice, setNotice] = useState<string | null>(null);

  function setPage(next: string) { window.location.hash = '#/' + next; setPageState(next); }

  useEffect(() => {
    const hash = () => setPageState(initialPage());
    const on = () => setOnline(true);
    const off = () => setOnline(false);
    window.addEventListener('hashchange', hash);
    window.addEventListener('online', on);
    window.addEventListener('offline', off);
    const close = openEventSocket((event) => setNotice(`${event.channel} at ${formatDate(event.timestamp)}`), setWsState);
    return () => { window.removeEventListener('hashchange', hash); window.removeEventListener('online', on); window.removeEventListener('offline', off); close(); };
  }, []);

  return <div className='min-h-screen bg-slate-950 text-slate-100'>
    <Header page={page} setPage={setPage} session={session} online={online} wsState={wsState} />
    <main className='mx-auto max-w-7xl space-y-6 px-4 py-6'>
      {notice && <div className='flex items-center justify-between rounded-xl border border-sky-500/30 bg-sky-950/40 px-4 py-3 text-sm text-sky-100'><span>{notice}</span><button onClick={() => setNotice(null)} className='font-semibold'>Dismiss</button></div>}
      {!session?.consentAcknowledged && <ConsentBanner onSession={setSession} />}
      {page === 'dashboard' && <Dashboard session={session} setPage={setPage} />}
      {page === 'allowlist' && <Allowlist session={session} />}
      {page === 'jobs' && <Jobs session={session} openDetail={(id) => setPage('job:' + id)} />}
      {page.startsWith('job:') && <JobDetail session={session} jobId={page.slice(4)} />}
      {page === 'plugins' && <Plugins session={session} />}
      {page === 'audit' && <Audit />}
      {page === 'exports' && <Exports session={session} />}
      {page === 'settings' && <Settings session={session} setSession={setSession} />}
      {page === 'docs' && <Docs />}
    </main>
  </div>;
}

function Dashboard({ session, setPage }: { session: OperatorSession | null; setPage: (p: string) => void }) {
  const [jobs, setJobs] = useState<RelayJob[]>([]);
  const [audit, setAudit] = useState<AuditEvent[]>([]);
  const [health, setHealth] = useState<string>('checking');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [reason, setReason] = useState('Emergency operator shutdown requested.');
  async function load() {
    setLoading(true); setError(null);
    try {
      const [h, j, a] = await Promise.all([api.health(), api.listJobs({ status: 'all', page: 1, pageSize: 20 }), api.listAudit({ page: 1, pageSize: 8 })]);
      setHealth(`${h.status} · ${formatDate(h.time)} · ${h.wsClients} ws clients`); setJobs(j.items); setAudit(a.items); await cacheSet('jobs', 'recent', j.items); await cacheSet('audit', 'recent', a.items);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Dashboard load failed');
      const cachedJobs = await cacheGet<RelayJob[]>('jobs', 'recent'); const cachedAudit = await cacheGet<AuditEvent[]>('audit', 'recent');
      if (cachedJobs) setJobs(cachedJobs); if (cachedAudit) setAudit(cachedAudit); setHealth('backend unavailable; showing cache when present');
    } finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);
  const active = jobs.filter((j) => ['running', 'queued', 'paused', 'ready'].includes(j.status));
  async function shutdown() {
    if (!reason.trim() || !confirm('Confirm emergency shutdown for all active jobs?')) return;
    try { const res = await api.shutdown(reason); alert(`Shutdown accepted. Terminated: ${res.terminatedJobIds.length}`); load(); } catch (err) { alert(err instanceof Error ? err.message : 'Shutdown failed'); }
  }
  return <section className='space-y-6'>
    <div className='grid gap-4 md:grid-cols-4'><Metric label='Backend' value={health} /><Metric label='Active queue' value={String(active.length)} /><Metric label='Recent jobs' value={String(jobs.length)} /><Metric label='Audit events' value={String(audit.length)} /></div>
    <StatusView loading={loading} error={error && jobs.length === 0 ? error : null} onRetry={load} empty={false}>
      <div className='grid gap-6 lg:grid-cols-3'>
        <div className='rounded-2xl border border-slate-800 bg-slate-900/70 p-5 lg:col-span-2'><h2 className='text-lg font-bold'>Live queue overview</h2><div className='mt-4 space-y-3'>{jobs.slice(0, 8).map((job) => <button key={job.jobId} onClick={() => setPage('job:' + job.jobId)} className='focus-ring flex w-full items-center justify-between rounded-xl bg-slate-950 p-3 text-left hover:bg-slate-800'><span><b>{job.name}</b><br /><small className='text-slate-400'>{job.jobId} · {formatDate(job.updatedAt)}</small></span><Badge value={job.status} /></button>)}{jobs.length === 0 && <p className='text-slate-400'>No jobs returned by the backend.</p>}</div></div>
        <div className='rounded-2xl border border-rose-800/70 bg-rose-950/30 p-5'><h2 className='text-lg font-bold text-rose-100'>Emergency shutdown</h2><p className='mt-2 text-sm text-rose-100/80'>Requires backend permission and records an audit event.</p><label className='mt-4 block text-sm'>Reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} className='mt-1 h-24 w-full rounded-lg border border-rose-900 bg-slate-950 p-3' /></label><button disabled={!can(session, 'shutdown:execute')} onClick={shutdown} className='focus-ring mt-3 w-full rounded-lg bg-rose-600 px-4 py-2 font-bold text-white'>Confirm shutdown</button></div>
      </div>
    </StatusView>
  </section>;
}

function Allowlist({ session }: { session: OperatorSession | null }) {
  const [items, setItems] = useState<TargetAllowlistEntry[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [form, setForm] = useState(emptyTarget); const [importText, setImportText] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function load() { setLoading(true); setError(null); try { const res = await api.listAllowlist({ status, search, page: 1, pageSize: 100 }); setItems(res.items); await cacheSet('allowlist', 'items', res.items); } catch (err) { setError(err instanceof Error ? err.message : 'Allowlist load failed'); const cached = await cacheGet<TargetAllowlistEntry[]>('allowlist', 'items'); if (cached) setItems(cached); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [status]);
  async function create() { if (!form.hostname || !form.address || !form.scopeTag || form.port < 1) return alert('Hostname, address, valid port, and scope tag are required.'); try { await api.createTarget(form); setForm(emptyTarget); load(); } catch (err) { alert(err instanceof Error ? err.message : 'Create failed'); } }
  async function importRecords() { try { const records = JSON.parse(importText); if (!Array.isArray(records)) return alert('Import JSON must be an array.'); const res = await api.importTargets(records); alert(`Accepted ${res.accepted}; rejected ${res.rejected.length}`); setImportText(''); load(); } catch (err) { alert(err instanceof Error ? err.message : 'Import failed'); } }
  async function revoke(id: string) { const reason = prompt('Revocation reason'); if (!reason) return; try { await api.revokeTarget(id, reason); load(); } catch (err) { alert(err instanceof Error ? err.message : 'Revoke failed'); } }
  return <section className='space-y-5'><h1 className='text-2xl font-black'>Target allowlist</h1><div className='grid gap-4 lg:grid-cols-3'><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Create target</h2>{(['hostname','address','protocol','scopeTag'] as const).map((k) => <label key={k} className='mt-3 block text-sm capitalize'>{k}<input value={form[k] || ''} onChange={(e) => setForm({ ...form, [k]: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label>)}<label className='mt-3 block text-sm'>Port<input type='number' value={form.port} onChange={(e) => setForm({ ...form, port: Number(e.target.value) })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label><label className='mt-3 block text-sm'>Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label><button disabled={!can(session,'allowlist:write')} onClick={create} className='mt-4 rounded-lg bg-sky-500 px-4 py-2 font-semibold'>Create</button></div><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5 lg:col-span-2'><h2 className='font-bold'>Import JSON array</h2><textarea value={importText} onChange={(e) => setImportText(e.target.value)} className='mt-3 h-32 w-full rounded-lg border border-slate-700 bg-slate-950 p-3' placeholder='[{"hostname":"host.internal","address":"10.0.0.10","protocol":"smb","port":445,"scopeTag":"engagement-a","notes":"approved","expiresAt":null}]' /><button disabled={!can(session,'allowlist:write')} onClick={importRecords} className='mt-3 rounded-lg bg-slate-700 px-4 py-2 font-semibold'>Import via backend</button></div></div><div className='flex gap-3'><input aria-label='Search allowlist' value={search} onChange={(e) => setSearch(e.target.value)} className='rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' placeholder='Search' /><select aria-label='Status filter' value={status} onChange={(e) => setStatus(e.target.value)} className='rounded-lg border border-slate-700 bg-slate-950 px-3 py-2'><option>all</option><option>approved</option><option>revoked</option></select><button onClick={load} className='rounded-lg bg-slate-700 px-4 py-2'>Apply</button></div><StatusView loading={loading} error={error && items.length === 0 ? error : null} empty={items.length === 0} onRetry={load}><Table headers={['Host','Address','Protocol','Scope','Status','Updated','Actions']} rows={items.map((t) => [t.hostname, `${t.address}:${t.port}`, t.protocol, t.scopeTag, <Badge value={t.status} />, formatDate(t.updatedAt), <button disabled={!can(session,'allowlist:write') || t.status === 'revoked'} onClick={() => revoke(t.targetId)} className='rounded bg-rose-600 px-3 py-1 text-sm'>Revoke</button>])} /></StatusView></section>;
}

function Jobs({ session, openDetail }: { session: OperatorSession | null; openDetail: (id: string) => void }) {
  const [jobs, setJobs] = useState<RelayJob[]>([]); const [targets, setTargets] = useState<TargetAllowlistEntry[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [job, setJob] = useState({ targetId: '', name: '', transportProfile: 'internal-default', requestedModules: '', notes: '', startMode: 'draft' as 'draft' | 'queued' }); const [validation, setValidation] = useState<string>('');
  async function load() { setLoading(true); setError(null); try { const [j, t] = await Promise.all([api.listJobs({ status: 'all', page: 1, pageSize: 100 }), api.listAllowlist({ status: 'approved', page: 1, pageSize: 100 })]); setJobs(j.items); setTargets(t.items); await cacheSet('jobs','items',j.items); } catch (err) { setError(err instanceof Error ? err.message : 'Jobs load failed'); const cached = await cacheGet<RelayJob[]>('jobs','items'); if (cached) setJobs(cached); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const payload = () => ({ targetId: job.targetId, name: job.name, transportProfile: job.transportProfile, requestedModules: job.requestedModules.split(',').map((m) => m.trim()).filter(Boolean), notes: job.notes });
  async function validate() { if (!job.targetId || !job.name) return alert('Target and job name are required.'); try { const res = await api.validateJob(payload()); setValidation(res.valid ? 'Valid: backend scope checks passed.' : 'Rejected: ' + res.issues.map((i) => i.message).join('; ')); } catch (err) { setValidation(err instanceof Error ? err.message : 'Validation failed'); } }
  async function create() { if (!validation.startsWith('Valid')) return alert('Run backend validation first.'); try { const res = await api.createJob({ ...payload(), startMode: job.startMode }); openDetail(res.job.jobId); } catch (err) { alert(err instanceof Error ? err.message : 'Create failed'); } }
  return <section className='space-y-5'><h1 className='text-2xl font-black'>Jobs</h1><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Job composer</h2><div className='grid gap-3 md:grid-cols-2'><label className='text-sm'>Approved target<select value={job.targetId} onChange={(e) => setJob({ ...job, targetId: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2'><option value=''>Select target</option>{targets.map((t) => <option key={t.targetId} value={t.targetId}>{t.hostname} · {t.scopeTag}</option>)}</select></label><label className='text-sm'>Job name<input value={job.name} onChange={(e) => setJob({ ...job, name: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label><label className='text-sm'>Transport profile<input value={job.transportProfile} onChange={(e) => setJob({ ...job, transportProfile: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label><label className='text-sm'>Requested modules<input value={job.requestedModules} onChange={(e) => setJob({ ...job, requestedModules: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' placeholder='comma separated registered module IDs' /></label><label className='text-sm md:col-span-2'>Notes<textarea value={job.notes} onChange={(e) => setJob({ ...job, notes: e.target.value })} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label></div><div className='mt-4 flex flex-wrap gap-3'><button disabled={!can(session,'jobs:write')} onClick={validate} className='rounded-lg bg-amber-500 px-4 py-2 font-semibold text-slate-950'>Validate against backend</button><button disabled={!can(session,'jobs:write')} onClick={create} className='rounded-lg bg-sky-500 px-4 py-2 font-semibold'>Create job</button><select value={job.startMode} onChange={(e) => setJob({ ...job, startMode: e.target.value as never })} className='rounded-lg border border-slate-700 bg-slate-950 px-3 py-2'><option value='draft'>draft</option><option value='queued'>queued</option></select></div>{validation && <p className='mt-3 text-sm text-slate-300'>{validation}</p>}</div><StatusView loading={loading} error={error && jobs.length === 0 ? error : null} empty={jobs.length === 0} onRetry={load}><Table headers={['Name','Target','Status','Created by','Updated','Actions']} rows={jobs.map((j) => [j.name, j.targetId, <Badge value={j.status} />, j.createdBy, formatDate(j.updatedAt), <button onClick={() => openDetail(j.jobId)} className='rounded bg-slate-700 px-3 py-1 text-sm'>Open</button>])} /></StatusView></section>;
}

function JobDetail({ session, jobId }: { session: OperatorSession | null; jobId: string }) {
  const [data, setData] = useState<{ job: RelayJob; session: any; events: AuditEvent[] } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [reason, setReason] = useState('Operator lifecycle action requested.');
  async function load() { setLoading(true); setError(null); try { setData(await api.getJob(jobId)); } catch (err) { setError(err instanceof Error ? err.message : 'Job load failed'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [jobId]);
  async function action(a: 'start'|'pause'|'resume'|'terminate') { if (!reason.trim()) return alert('Reason is required.'); try { await api.jobAction(jobId, a, reason); load(); } catch (err) { alert(err instanceof Error ? err.message : 'Action failed'); } }
  return <StatusView loading={loading} error={error} empty={!data} onRetry={load}>{data && <section className='space-y-5'><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><div className='flex flex-wrap items-center justify-between gap-4'><div><h1 className='text-2xl font-black'>{data.job.name}</h1><p className='text-sm text-slate-400'>{data.job.jobId} · target {data.job.targetId}</p></div><Badge value={data.job.status} /></div><div className='mt-4 grid gap-3 md:grid-cols-4'><Metric label='Created' value={formatDate(data.job.createdAt)} /><Metric label='Updated' value={formatDate(data.job.updatedAt)} /><Metric label='Operator' value={data.job.createdBy} /><Metric label='Session' value={data.session?.state || 'none'} /></div><label className='mt-4 block text-sm'>Reason for lifecycle action<input value={reason} onChange={(e) => setReason(e.target.value)} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2' /></label><div className='mt-4 flex flex-wrap gap-2'>{(['start','pause','resume','terminate'] as const).map((a) => <button key={a} disabled={!can(session,'jobs:write')} onClick={() => action(a)} className='rounded-lg bg-slate-700 px-4 py-2 font-semibold capitalize hover:bg-slate-600'>{a}</button>)}</div></div><div className='grid gap-5 lg:grid-cols-2'><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Session metadata</h2><pre className='mt-3 overflow-auto rounded-lg bg-slate-950 p-3 text-sm text-slate-300'>{JSON.stringify(data.session?.capturedMetadata || {}, null, 2)}</pre></div><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Timeline</h2><div className='mt-4 space-y-3'>{data.events.map((e) => <div key={e.eventId} className='rounded-lg bg-slate-950 p-3'><p className='font-semibold'>{e.type}</p><p className='text-sm text-slate-300'>{e.message}</p><p className='text-xs text-slate-500'>{formatDate(e.timestamp)}</p></div>)}{data.events.length === 0 && <p className='text-slate-400'>No timeline events returned.</p>}</div></div></div></section>}</StatusView>;
}

function Plugins({ session }: { session: OperatorSession | null }) {
  const [plugins, setPlugins] = useState<PluginDefinition[]>([]); const [jobs, setJobs] = useState<RelayJob[]>([]); const [selected, setSelected] = useState(''); const [jobId, setJobId] = useState(''); const [params, setParams] = useState('{}'); const [result, setResult] = useState('');
  useEffect(() => { Promise.all([api.listPlugins(), api.listJobs({ status: 'all', page: 1, pageSize: 100 })]).then(([p,j]) => { setPlugins(p.items); setJobs(j.items); }).catch((e) => setResult(e.message)); }, []);
  const targetId = jobs.find((j) => j.jobId === jobId)?.targetId || '';
  async function validate() { try { setResult(JSON.stringify(await api.validatePlugin(selected, { jobId, targetId, parameters: JSON.parse(params) }), null, 2)); } catch (e) { setResult(e instanceof Error ? e.message : 'Validation failed'); } }
  async function run() { const reason = prompt('Reason for plugin run'); if (!reason) return; try { setResult(JSON.stringify(await api.runPlugin(selected, { jobId, targetId, parameters: JSON.parse(params), reason }), null, 2)); } catch (e) { setResult(e instanceof Error ? e.message : 'Run failed'); } }
  return <section className='space-y-5'><h1 className='text-2xl font-black'>Plugin hooks</h1><div className='grid gap-5 lg:grid-cols-2'><div className='space-y-3'>{plugins.map((p) => <button key={p.pluginId} onClick={() => setSelected(p.pluginId)} className={`w-full rounded-2xl border p-4 text-left ${selected === p.pluginId ? 'border-sky-400 bg-sky-950/40' : 'border-slate-800 bg-slate-900'}`}><h2 className='font-bold'>{p.name}</h2><p className='text-sm text-slate-300'>{p.description}</p><p className='mt-2 text-xs text-slate-400'>Protocols: {p.allowedTargetProtocols.join(', ')} · dry-run {String(p.supportsDryRun)}</p></button>))}{plugins.length === 0 && <StatusView empty emptyText='No plugin definitions returned by backend.'>x</StatusView>}</div><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Dry-run and execution</h2><label className='mt-3 block text-sm'>Job<select value={jobId} onChange={(e) => setJobId(e.target.value)} className='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2'><option value=''>Select job</option>{jobs.map((j) => <option key={j.jobId} value={j.jobId}>{j.name} · {j.status}</option>)}</select></label><label className='mt-3 block text-sm'>Parameters JSON<textarea value={params} onChange={(e) => setParams(e.target.value)} className='mt-1 h-28 w-full rounded-lg border border-slate-700 bg-slate-950 p-3' /></label><div className='mt-4 flex gap-3'><button disabled={!selected || !jobId || !can(session,'plugins:run')} onClick={validate} className='rounded-lg bg-amber-500 px-4 py-2 font-semibold text-slate-950'>Dry-run validate</button><button disabled={!selected || !jobId || !can(session,'plugins:run')} onClick={run} className='rounded-lg bg-sky-500 px-4 py-2 font-semibold'>Run plugin</button></div>{result && <pre className='mt-4 overflow-auto rounded-lg bg-slate-950 p-3 text-sm'>{result}</pre>}</div></div></section>;
}

function Audit() { const [items,setItems]=useState<AuditEvent[]>([]); const [filter,setFilter]=useState({ jobId:'', operatorId:'', type:'' }); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); async function load(){setLoading(true);setError(null);try{const r=await api.listAudit({ ...filter, page:1, pageSize:100 });setItems(r.items);await cacheSet('audit','items',r.items);}catch(e){setError(e instanceof Error?e.message:'Audit load failed');const c=await cacheGet<AuditEvent[]>('audit','items');if(c)setItems(c);}finally{setLoading(false);}} useEffect(()=>{load();},[]); return <section className='space-y-5'><h1 className='text-2xl font-black'>Audit log</h1><div className='flex flex-wrap gap-3'>{(['jobId','operatorId','type'] as const).map(k=><input key={k} aria-label={k} placeholder={k} value={filter[k]} onChange={e=>setFilter({...filter,[k]:e.target.value})} className='rounded-lg border border-slate-700 bg-slate-950 px-3 py-2'/>)}<button onClick={load} className='rounded-lg bg-slate-700 px-4 py-2'>Filter</button></div><StatusView loading={loading} error={error && items.length===0?error:null} empty={items.length===0} onRetry={load}><Table headers={['Time','Type','Operator','Job','Message']} rows={items.map(e=>[formatDate(e.timestamp),e.type,e.operatorId,e.jobId || '—',e.message])}/></StatusView></section>; }

function Exports({ session }: { session: OperatorSession | null }) { const [jobs,setJobs]=useState<RelayJob[]>([]); const [selected,setSelected]=useState<string[]>([]); const [includeAudit,setIncludeAudit]=useState(true); const [includeMetadata,setIncludeMetadata]=useState(true); const [includeNotes,setIncludeNotes]=useState(true); const [result,setResult]=useState<ExportBundleRecord|null>(null); useEffect(()=>{api.listJobs({status:'all',page:1,pageSize:100}).then(r=>setJobs(r.items)).catch(e=>alert(e.message));},[]); async function create(){ if(selected.length===0)return alert('Select at least one job.'); try{const r=await api.createExport({jobIds:selected,includeAudit,includeMetadata,includeNotes,noteSections:['scope','timeline','operator-notes']}); const full=await api.getExport(r.exportId); setResult(full.export); }catch(e){alert(e instanceof Error?e.message:'Export failed');}} return <section className='space-y-5'><h1 className='text-2xl font-black'>Evidence export</h1><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Select jobs</h2><div className='mt-3 grid gap-2 md:grid-cols-2'>{jobs.map(j=><label key={j.jobId} className='rounded-lg bg-slate-950 p-3'><input type='checkbox' checked={selected.includes(j.jobId)} onChange={e=>setSelected(e.target.checked?[...selected,j.jobId]:selected.filter(id=>id!==j.jobId))}/> <span className='ml-2'>{j.name} · {j.status}</span></label>)}</div><div className='mt-4 flex flex-wrap gap-4 text-sm'><label><input type='checkbox' checked={includeAudit} onChange={e=>setIncludeAudit(e.target.checked)}/> Audit</label><label><input type='checkbox' checked={includeMetadata} onChange={e=>setIncludeMetadata(e.target.checked)}/> Metadata</label><label><input type='checkbox' checked={includeNotes} onChange={e=>setIncludeNotes(e.target.checked)}/> Notes</label></div><button disabled={!can(session,'exports:write')} onClick={create} className='mt-4 rounded-lg bg-sky-500 px-4 py-2 font-semibold'>Generate with backend</button></div>{result&&<div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Export {result.exportId}</h2><p className='text-sm text-slate-300'>Jobs: {result.summary.jobCount}; audit events: {result.summary.auditEventCount}</p><button onClick={()=>downloadJson(`relayjack-${result.exportId}.json`, result)} className='mt-3 rounded-lg bg-emerald-600 px-4 py-2 font-semibold'>Download JSON</button></div>}</section>; }

function Settings({ session, setSession }: { session: OperatorSession | null; setSession: (s: OperatorSession | null) => void }) { return <section className='space-y-5'><h1 className='text-2xl font-black'>Settings</h1><div className='rounded-2xl border border-slate-800 bg-slate-900 p-5'><h2 className='font-bold'>Session</h2><pre className='mt-3 overflow-auto rounded-lg bg-slate-950 p-3 text-sm'>{JSON.stringify(session, null, 2)}</pre><button onClick={()=>{localStorage.removeItem('relayjack.session');setSession(null);}} className='mt-4 rounded-lg bg-slate-700 px-4 py-2'>Clear local acknowledgement</button></div></section>; }
function Docs() { return <section className='rounded-2xl border border-slate-800 bg-slate-900 p-6 leading-7 text-slate-200'><h1 className='text-2xl font-black text-white'>Operator workflow</h1><p className='mt-3'>RelayJack coordinates scoped workflow records through backend allowlist, job, plugin, audit, and export APIs. The frontend does not implement exploit payloads or bypass backend scope checks.</p><ul className='mt-4 list-disc pl-6'><li>Acknowledge authorized use to receive backend permissions.</li><li>Create or import approved targets before creating jobs.</li><li>Validate jobs and plugin runs before execution requests.</li><li>Use audit and exports pages for engagement evidence generated by backend records.</li><li>If the backend is unavailable, cached data may be shown for review, but successful mutations are never faked.</li></ul></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className='rounded-2xl border border-slate-800 bg-slate-900/80 p-4'><p className='text-xs uppercase tracking-wide text-slate-500'>{label}</p><p className='mt-2 break-words text-lg font-bold text-white'>{value}</p></div>; }
function Badge({ value }: { value: string }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${statusClass(value)}`}>{value}</span>; }
function Table({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className='overflow-x-auto rounded-2xl border border-slate-800'><table className='min-w-full divide-y divide-slate-800 bg-slate-900'><thead><tr>{headers.map(h=><th key={h} className='px-4 py-3 text-left text-xs uppercase tracking-wide text-slate-400'>{h}</th>)}</tr></thead><tbody className='divide-y divide-slate-800'>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className='px-4 py-3 text-sm text-slate-200'>{c}</td>)}</tr>)}</tbody></table></div>; }
